### ISSUE TITLE
How to change the size of the digits

### ISSUE THREAD

**Issue by HuntFeng** [erco77/nixieclock#1]
I tried to change the `FONTWIDTH` and `FONTHEIGHT` in `NixieDisplay.H`, but that affects the spacing between digits.

**Comment by erco77** [comment]
The digits are fixed height because they're actually XPM images.
Nixieclock was designed before FLTK provided Fl_Image::scale(), so NixieDisplay's API doesn't make use of it, but that's probably a way to easily implement scaling of the images, and thus scaling of the font -- patches welcome!

**Comment by HuntFeng** [comment]
> The digits are fixed height because they're actually XPM images.
> Nixieclock was designed before FLTK provided Fl_Image::scale(), so NixieDisplay's API doesn't make use of it, but that's probably a way to easily implement scaling of the images, and thus scaling of the font -- patches welcome!

I tried to directly scale the images, but the final display shows some broken things... Maybe I should try your method Fl_Image::scale().
Sorry, I really don't know too much of C++, this is too hard for me. Maybe I will try this again sometime in the future.

Anyway, thanks for you answer, at least I know where to go now.

**Comment by erco77** [comment]
What are you trying to do, just make the clock digits larger?

If so, you can use the Ctrl+ hotkey to make the whole clock larger (or cloverleaf+ on a mac), assuming you linked against FLTK 1.4.x. In FLTK 1.4 they added that feature to zoom the entire application using Ctrl+ / Ctrl-
I just tried it with my nixieclock, running three clocks, zooming each slightly larger. It does work well with no code modifications needed.

![screenshot-scaled-nixieclock](https://user-images.githubusercontent.com/6484779/118061172-44038d00-b349-11eb-8800-d2e8e2429c55.jpg)

**Comment by HuntFeng** [comment]
> What are you trying to do, just make the clock digits larger?
> 
> If so, you can use the Ctrl+ hotkey to make the whole clock larger (or cloverleaf+ on a mac), assuming you linked against FLTK 1.4.x. In FLTK 1.4 they added that feature to zoom the entire application using Ctrl+ / Ctrl-
> I just tried it with my nixieclock, running three clocks, zooming each slightly larger. It does work well with no code modifications needed.
> 
> ![screenshot-scaled-nixieclock](https://user-images.githubusercontent.com/6484779/118061172-44038d00-b349-11eb-8800-d2e8e2429c55.jpg)

Thank you! I upgraded my FLTK to 1.4, that works!
